### ISSUE TITLE
Resize interface font size

### ISSUE THREAD

**Issue by davidbarratt** [sqlectron/sqlectron-gui#340] opened 2017-08-20 20:34 UTC
I find the interface is really hard to read (i.e. the sidebar, etc.) It would be really helpful if you could resize the interface.

Alternatively, perhaps providing a custom stylesheet (which is what Atom does) would be best?

**Comment by maxcnunes** [comment] 2017-08-20 21:19
Have you tried `zoomFactor`setting?
https://github.com/sqlectron/sqlectron-gui/blob/master/docs/app/configuration-file.md

**Comment by BornaP** [comment] 2017-08-30 12:14
Duplicate of #330 , so I'll close the issue.

**Closed by BornaP** 2017-08-30 12:14 UTC
