### ISSUE TITLE
v1.37.0 not starting on Debian Buster

### ISSUE THREAD

**Issue by Misterrenaud** [sqlectron/sqlectron-gui#679] opened 2021-08-16 13:59 UTC
Hello,
I tried to install the deb package amd64 on my Debian Buster, and I encouter this error when in start the app : 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'lodash.clonedeep'
Require stack:
- /opt/sqlectron/resources/app.asar/out/browser/core/db.js
- /opt/sqlectron/resources/app.asar/out/browser/core/index.js
- /opt/sqlectron/resources/app.asar/out/browser/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/sqlectron/resources/app.asar/out/browser/core/db.js:69:42)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

```

Version 1.36.0 works perfectly

**Comment by MasterOdin** [comment] 2021-08-16 14:00
Duplicate of #678. This is fixed in master, I'm prepping a 1.37.1 release.

**Closed by MasterOdin** 2021-08-16 14:00 UTC
