### ISSUE TITLE
Windows install of Postgres Intercepts external connections

### ISSUE THREAD

**Issue by SyriiAdvent** [sqlectron/sqlectron-gui#502] opened 2020-08-05 15:05 UTC
When attempting to "test" a connection you get an error saying "this "user" doesn't exist on this connection."
![wrong user](https://i.imgur.com/mQ8G6fj.png)

However, that shouldn't happen. Its checking local Postgres users first?

If you just save the ssh connection instead of "testing" it, The connection works 100% fine.

![connection](https://i.imgur.com/olikc4L.png)

**Comment by MasterOdin** [comment] 2020-08-06 21:10
When you say "ssh connection", you're just doing a regular connection without the ssh tunnel options enabled?

**Comment by SyriiAdvent** [comment] 2020-08-07 16:14
Correct. it's looking for "Advent" when I specifically put in "rudy."
my local has a user named Advent however

**Comment by MasterOdin** [comment] 2020-08-29 01:53
Alright, confirmed what's going on. It looks like when you do not fill in a database name, it will attempt to use a set default database, which for postgresql is `postgres`. However, it does not do this when testing the connection, falling back to how the library determines default database name, which for postgres is the username of the current OS.

Anyway, fix will be incoming shortly for the imminent 1.32.0 release

**Closed** 2020-09-04 02:22 UTC
Labels: bug

**Comment by jkvyff** [comment] 2020-09-18 22:05
If someone else has this bug before the next release, this is where you would put the default database name when testing a connection.
<img width="848" alt="Screen Shot 2020-09-18 at 2 57 30 PM" src="https://user-images.githubusercontent.com/8835646/93649210-4c751500-f9c0-11ea-8cdb-46a378bbd72e.png">
