### ISSUE TITLE
Issue in opening file on SQLectron

### ISSUE THREAD

**Issue by moazzam1ali** [sqlectron/sqlectron-gui#557] opened 2021-01-05 01:23 UTC
I just started learning SQL. I have downloaded **SQLectron** and connect it to the **Postgresql**. I am trying to open a query using **crtl+o**. As i select the file to open, SQLectron isn't **respoinding**..
what should I do? any suggestions?
thank you..

**Comment by MasterOdin** [comment] 2021-01-07 14:38
Are you using the latest version of sqlectron as this should be fixed there.

**Comment by MasterOdin** [comment] 2021-02-13 03:36
Cannot reproduce. Sometimes electron does take a while to show the file dialog, but there's not much I can do about that unfortunately.

**Closed by MasterOdin** 2021-02-13 03:36 UTC
Labels: awaiting feedback
