### ISSUE TITLE
Editor moving the cursor after each keystroke

### ISSUE THREAD

**Issue by timothy-clifford** [sqlectron/sqlectron-gui#284] opened 2017-01-18 01:04 UTC
After installing v1.19.0 my sql query editor moves the cursor to the end of the query after every keystroke. This is rather annoying when editing a query.

**Comment by maxcnunes** [comment] 2017-01-19 12:26
What is your OS? I don't see this happening on MacOS.

**Comment by timothy-clifford** [comment] 2017-01-20 02:19
Mac OSX Sierra.
I copied the SQL from a .sql file, pasted in the editor, and then looked to change it.

**Comment by maxcnunes** [comment] 2017-01-20 10:11
I thought maybe was because of the copy and past. But I still can't reproduce that. Maybe there is some especial character in that file that is causing it.
Does the problem occur if you past this query below?
```sql
SELECT some_column
FROM some_table
WHERE some_table.other_column = 'some_value';
```

**Comment by timothy-clifford** [comment] 2017-01-22 22:48
Nope - still occurring.
I do have another weird thing which may be causing problems: I'm looking at a SQL Server machine and I can see all the DBs fine, but I see a message flashing in the bottom left corner "Loading list of tables...". It seems to have stalled loading the tables for a DB.

**Comment by maxcnunes** [comment] 2017-01-22 23:15
So that is probably the reason. There is an issue open for that already https://github.com/sqlectron/sqlectron-gui/issues/286.
I will close it since it looks is duplicated. Let me know if it still happening after that issue is solved.

**Closed by maxcnunes** 2017-01-22 23:15 UTC

**Comment by timothy-clifford** [comment] 2017-01-22 23:19
OK - thanks.
