### ISSUE TITLE
Connecting mysql with auth_socket

### ISSUE THREAD

**Issue by Th3BiSh0p** [sqlectron/sqlectron-gui#448] opened 2018-08-30 14:00 UTC
Hello,

I'm trying to connect to my local mysql server and I'm getting a
```
Connection Error
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
Is there a way to access my server with sqlectron ?

Thanks

**Comment by barneydmedia** [comment] 2018-09-07 01:40
I believe this is a duplicate of #442 which I plan to look into soon.

**Closed** 2018-09-07 19:12 UTC
Labels: duplicate
