### ISSUE TITLE
Open query from file

### ISSUE THREAD

**Issue by jbencina** [sqlectron/sqlectron-gui#223] opened 2016-09-12 03:34 UTC
I tried searching through the issues and online, but I can't seem to find any way to open a saved query into a tab (using Windows GUI client). My menu just allows to Save Query.

**Comment by abourget** [comment] 2016-10-12 18:07
would be awesome that the state of last window is saved..

I love that queries are saved to plain-text files.. that's great!

**Comment by maxcnunes** [comment] 2016-10-12 19:04
I guess we could achieve that by adding support to save the current window state to a folder. Each tab would become a different file. So adding support to open queries from a folder would kind of restore the window state.

**Comment by marvinrichter** [comment] 2016-12-08 13:51
The problem @jbencina describes does not have to do with saving the current state of a window.

The problem is, that the GUI does provide a way (and even a shortcut, ctrl+s) to save the query of a Tab as a *.sql file but it doesn't allow to open such a file.

So the feature would be to have the option (and maybe a shortcut, e.g. ctrl+o) for open any *.sql file as a new Tab.

**Comment by BornaP** [comment] 2016-12-08 14:40
@marvinrichter You're right about that, but Max and abourget were talking about saving whole state of lastly opened window, which is another feature.

I'll try to implement opening query from file option (with a shortcut too) as soon as I catch some time. Hopefully this weekend.

**Comment by thoma87** [comment] 2017-04-11 17:28
Any update on this? Without this functionality I have to open .sql files using a text editor and then paste into  new window. Painful!

**Comment by BornaP** [comment] 2017-04-19 07:52
Hey @thoma87 unfortunately no progress on this. Paid job kicked in heavy. I'll try and implement this as soon as possible. If you have time meanwhile, you are more than welcome to make a PR.

**Comment by acotillard** [comment] 2017-08-02 16:11
Hi @BornaP ,

Any update about this request ?
This function will be so helpful :smiley: 

Best,

**Comment by BornaP** [comment] 2017-08-06 18:41
Hey @acotillard ,

Finally caught some time for this. I'll notify you here when PR is merged and new release has been published :)

Cheers!

**Closed** 2017-08-06 19:27 UTC
Labels: enhancement

**Comment by BornaP** [comment] 2017-08-07 08:30
@acotillard new release with this feature is up! :)

**Comment by acotillard** [comment] 2017-08-07 10:21
Thanks @BornaP  this feature is so helpful !! :smile: 

I just noticed 2 things : 

1/ When you open a sql file, he is open in the actual tab you are, so that overwrites the tab in use if you have wrote something inside.

Idea : Open sql file in a new tab.

2/ Actually it's not possible to select several sql files.

Do you think it will be interesting to add this ?

Cheers!

**Comment by BornaP** [comment] 2017-08-07 10:26
Hey @acotillard ,glad you find it helpful.

About proposal, well it's bit more complicated than that, because every tab is related to a certain database. I guess we could do that so that all queries selected are spawned as tabs in a current database connection. I will try to work that out soon.

Cheers!
