### ISSUE TITLE
sqlectron 1.32 from .deb don't allow me to open a .sql file or a query into a sql file.

### ISSUE THREAD

**Issue by benjaminW78** [sqlectron/sqlectron-gui#544] opened 2020-11-10 15:15 UTC
Hello i just migrated over the version 1.32 of sqlectron a week ago and i saw that i wasn't able to open nor save a query in one tap into a .sql file. no errors are to be seen in the devtools.

i'm running on a fresh ubuntu 20.04

button File>Open query open a window to search for my file but whenever i select one window close but the tab where the query should be stay empty. 

same for File> Save query which follow the same process and when after i look into my FS to check the file is here and what it contain i don't find the file and obviously the content well was not saved into a file.

**Comment by MasterOdin** [comment] 2020-11-10 23:46
Duplicate of #540.

I am going to cut a 1.32.1 release today that will bundle up three bugfixes off master, including the one for this.

**Closed by MasterOdin** 2020-11-10 23:46 UTC
