### ISSUE TITLE
Looking for new contributors

### ISSUE THREAD

**Issue by maxcnunes** [sqlectron/sqlectron-gui#433] opened 2018-03-03 13:36 UTC
I guess I have not been using SQL databases for the last 2 years, which means no Sqlectron as well. I tried to maintain this project as much as I could but I have lost the interest spending my personal time on something I don’t use anymore. That is why I'm formally pausing my work on its maintenance 😢 

If you use it and you are interested in keeping this project alive. Please, contact me over here and I will make sure to help you out with anything you need for a smooth maintainer transition.

Overall, thanks to all users and contributors ❤️

**Comment by JamieOnUbuntu** [comment] 2018-03-03 22:54
Thanks for your work, I have found this tool very useful! :)

**Comment by logavanc** [comment] 2018-03-04 18:23
Beautiful program, bummed to hear you are dropping it.

**Comment by arturock** [comment] 2018-03-05 17:46
Thank you very much for all your work on this. On Linux, Sqlectron is invaluable!

**Comment by sscholle** [comment] 2018-03-06 12:24
@maxcnunes I use it! Interested in becoming maintainer.

**Comment by VinceAsRam** [comment] 2018-03-09 15:54
Thank you for developing a Wonderful Application. We will wait until someone will volunteer to improve the development of SQLElectron.

**Comment by workguy66** [comment] 2018-03-13 11:48
The best one on linux for mysql, mysql workbench is awful

**Comment by jacob-israel-turner** [comment] 2018-03-13 16:07
I just came across this project a couple of weeks ago and I love it.  Not sure I have the time to take point, but I'd be happy to help maintain it.

**Comment by arjunkesava** [comment] 2018-03-15 13:27
I hope, people will fork it and develop on it,
(I did one just now)

**Comment by sscholle** [comment] 2018-03-15 15:10
I guess all we need to do is submit PRs back to @maxcnunes ? I'm keen, Ive already found a bug that I just need to fix asap :D

**Comment by BakirRabiaSalma** [comment] 2018-03-16 08:40
thank you maxcnunes ,i'm working to improve it so if i'd ask for something , i hope you 'll help me.

**Comment by BornaP** [comment] 2018-03-16 17:30
Max, thanks again for all the help and advices you gave to us, contributors. I completely understand you've lost interest maintaining something that you don't use. I can relate to that 😅 

I'd just like to point out to future maintainer, that UI code may use some good refactoring. Max is world class engineer, but I think lot of contributions to GUI repo were from people (including myself) that were getting started with React couple of years ago. I think the same was with Max, it was learn-new-technology-make-something-useful kind of project, if I'm not wrong :) Backend part should be good, Max got that covered well.

All in all, what was supposed to be learn&fun project turned into something really useful and that's true beauty of open source. I know people will mostly see the value in the app they use (_Sqlectron_), but there's additional value to that. Max helped me, and many others, to get started with Open Source, and technologies there were new to us. Speaking on my behalf, he was very patient teacher and OSS maintainer. I've never felt a bit of annoyance in his replies, no matter how dull my question was. That guy is true Open Source Hero if you ask me. @Github you hear me? :D 

Ps. For future maintainer(s): Maybe you could use Open Collective platform for covering part of your expenses?

**Comment by tjbarber** [comment] 2018-03-26 22:35
I would love to be a part of Sqlectron's future, but would definitely want to be working with a few others. 

I came to Sqlectron just today while looking for a good relational database GUI that isn't absolute trash on Linux. Not only is it good, it's really good. I don't have time to be the sole maintainer of it, but if there are at least a couple others that would like to spend some time making this project even more awesome I would love to be a part of it.

**Comment by joereynolds** [comment] 2018-03-27 15:42
Since this is not maintained anymore, I'd like to recommend [dbeaver](https://github.com/dbeaver/dbeaver) as an alternative.
It's not as pleasing to the eye but it's very featureful and well used.

**Comment by mahongquan** [comment] 2018-04-20 03:11
i fork it,and change a lot on it.[https://github.com/mahongquan/sqlectron-gui](url)

**Comment by fuzzy76** [comment] 2018-04-25 11:56
Since several people have expressed interest, this shouldn't really be a problem. @mahongquan did you try to contanct @maxcnunes as he said in the issue? Or @sscholle ?

**Comment by sscholle** [comment] 2018-05-25 13:27
just fork it @fuzzy76 - maybe link your fork in this issue - and update your README to the changes you make

**Comment by maxcnunes** [comment] 2018-05-25 14:52
I was contacted by mahongquan weeks ago. But I didn't agree with the way the changes were driven on his fork (mostly commit messages and the way changes were done). I spent a long time building this app and I hope to pass the ownership to someone who shares few common guides:
* keep the commit history clean, so it makes easier for contributors to maintain the project (a great article about that: https://chris.beams.io/posts/git-commit/)
* keep the master branch clean, do not commit debugging stuff that should live a separated development branch

I don't want to be picky. I'm just thinking about the future of the project to keep it easy for other contributors to join and understand the project history and codebase.

**Comment by dsofeir** [comment] 2018-06-15 09:20
@maxcnunes Have you found a new maintainer?

SQLECTRON is a very useful tool on Linux and seems to have quite the following. It would be a shame to see it fall in to decline. If you are yet to find some I would be interested in discussing it.

**Comment by maxcnunes** [comment] 2018-06-15 14:20
@dsofeir I'm still waiting for someone to take it over :) If you prefer to discuss it in private just DM me on Twitter @maxcnunes.

**Comment by scottjbarr** [comment] 2018-06-27 09:53
@mahongquan looks like https://github.com/mahongquan/sqlectron-gui looks quite active.

**Comment by fuzzy76** [comment] 2018-07-11 20:53
Activity trumps purity I guess

**Comment by scottjbarr** [comment] 2018-07-11 22:54
@fuzzy76 If no one takes over, one of the active forks will possibly become the new thing. I'm definitely not saying "busy" is good.

**Comment by iamareebjamal** [comment] 2018-07-12 18:33
@scottjbarr Just see the commit messages and the content of those and message by @maxcnunes above and you'll understand. Standards in open source projects are very important and commits should be meaningful atomic unit of code change which have 1:1 correspondence with a feature or bugfix

**Comment by RHieger** [comment] 2018-07-16 22:14
I am a current student at Woz U and just finished a course in ReactJS. I see that your project relies on React (at least partially). While I am in the 24-Week bootcamp program, I might not be able to contribute much, but I do like the interface of your application, and as time might allow in the near future, I would be happy to contribute and interested in doing so.

My focus has been and remains Full Stack Web Development/Design, and a tool such as **sqlectron** might be very useful and expedient for that work.

Thank you for your development work on this project thus far, and I wish you the best in all your future and current development work.

**Comment by dflock** [comment] 2018-09-05 23:31
So... @barneydmedia just did a new release of SQLElectron: https://github.com/sqlectron/sqlectron-gui/releases :tada: - so is this issue closed, then?

**Comment by barneydmedia** [comment] 2018-09-06 21:18
There is a new build out, and I plan on taking a look at some of the other issues. I would like to see the project continue, personally.

**Comment by dsofeir** [comment] 2018-09-06 23:47
@maxcnunes @barneydmedia I started using sqlectron has an alternative to MySQL Workbench and the lack of a comparable Atom package. Specifically there is no Atom package which offers SSH tunneling to a MySQL host.

Since this discussion is about the continuation/future of the project. Do you think packaging sqlectron as an Atom package would be a good future direction? This would expand the potential user-base and potentially attract new contributors.

**Comment by barneydmedia** [comment] 2018-09-07 01:28
I think it would be cool, and I think it would be a good thing. I also think it would be a lot of work and could potentially split the codebase in consequential ways. 

I'm not able to do it, but I also wouldn't be against someone else making an effort on a separate fork to later add/merge. I would also love to see more users and contributors here.

**Comment by maxcnunes** [comment] 2018-09-08 15:05
Hey @barneydmedia, or anyone who comes after you, feel free to close this issue and remove the unmaintained labels from the project if you think you are ready to take over the project. 🙏 🎉 

For others interested in taking over, I just answered an email to @dsofeir with details of how to do it, and it is the same for anyone else:
> I'm looking for people who can improve this project or at least keep the existing quality. In my opinion, the best way to analyze it is through a PR so I can check those details. For example, @barneydmedia sent a PR https://github.com/sqlectron/sqlectron-gui/pull/436 and I added him as a contributor. Then he merged and released a new version himself.

**Comment by Gusbenz** [comment] 2018-11-13 16:48
@barneydmedia are you the new maintainer on this project? If so, could we close this issue?

**Comment by shajanjp** [comment] 2019-04-04 05:25
Thanks for building this. I was planning to add support for noSQL databases(mongo).

**Comment by rathboma** [comment] 2019-04-19 16:01
Hey guys, looks like the project has sort of slipped back into non-maintenance since @barneydmedia took over last year.

I'm interested in taking over the project, website, et al. I have a junior dev who is willing to help with the maintenance work, so that's the start of a small team! 

We'll start submitting some PRs and see how that goes.

**Comment by vexhack** [comment] 2019-04-19 17:51
@rathboma feel free to ping me on issues if you'd like - I can try to offer some support

**Comment by rathboma** [comment] 2019-04-20 01:21
Thanks! My biggest concern with a take-over is that there are a lot of outdated dependencies that need upgrading. We'll start small :-)

**Comment by rathboma** [comment] 2019-04-20 01:32
One question -- when debugging it only shows me stack traces within `bundle.js`, the webpacker dev config seems to be correct. Have any of the prior maintainers figured this out?

**Comment by mahongquan** [comment] 2019-04-22 00:38
my fork has upgrade to newest depends

**Comment by rathboma** [comment] 2019-04-22 20:25
@mahongquan nice! Have you thought about submitting a PR?

**Comment by manngo** [comment] 2019-05-02 01:41
@rathboma I’m a bit confused here. Are you now the maintainer? If so, that’s good news!

**Comment by rathboma** [comment] 2019-05-02 20:46
Not yet! But I'm hoping to slowly ramp up my involvement in the project and get my junior dev on board to help too.

**Comment by izikorgad** [comment] 2019-05-28 14:11
@rathboma, I'll be happy to assist and maintain this project (did some small contribution in the past...) please contact me so we can coordinate.

**Comment by benjaminW78** [comment] 2019-06-11 10:11
so is the project able to be maintenaid by @rathboma ? i think i may be submitting a PR to add shortCut to the connected interface (to ease the keyboard navigation inside the gui interface)

**Comment by JARVIS-AI** [comment] 2019-06-12 21:04
one year passed, so its maintaining yes ?

**Comment by rathboma** [comment] 2019-06-17 14:38
Hey! I'm on the maintainer list now. I'm just wrapping up some project work and will be able to take more of a look at the project at the end of the month and actively start moderating and contributing. Stay tuned! My first task will be bringing dependencies up to date and fixing any critical bugs.

**Comment by krolow** [comment] 2019-06-19 00:27
thx @rathboma it's going to be great to have someone active in the project! I'd love to help as much as I can but it's not a software that I'm using nowadays (I'm using relational db 😞) but I can for sure help in code review looking for to see yours PR'S @rathboma 💪  👏

**Comment by ferm10n** [comment] 2019-07-25 20:18
@mahongquan why haven't you submitted a pull request yet?

**Comment by vexhack** [comment] 2019-07-26 01:24
@rathboma please ping me or whatever on certain issues - I can see what I can do

**Comment by rathboma** [comment] 2019-07-26 02:28
Honestly folks I thought my work would be letting up, but it's not really, so I'm not sure how much time I'm going to actually have to work on the project :-(

**Comment by the94air** [comment] 2019-09-09 14:48
@rathboma Since you don't have time a Discord server is a good idea to let anyone collaborate to bring this project back.

**Comment by the94air** [comment] 2019-09-17 06:18
> @rathboma Since you don't have time a Discord server is a good idea to let anyone collaborate to bring this project back.

cc @maxcnunes @BornaP @barneydmedia @krolow @rathboma

**Comment by maxcnunes** [comment] 2019-10-02 14:22
Not sure if a Discord server would make much difference. There is already a Slack team but there have not been any interactions there since I announced I was stopping my contribution to the project. Anyway, the team still available if anyone wants to use it - https://sqlectron.herokuapp.com/

**Comment by DCdeBrabander** [comment] 2019-10-08 08:51
Don't know which version is currently latest / the go to, but I am also interested to do some UX stuff if need be. Current (official) version I use, on Linux, lacks some basic features like 'in place editing'. 

If Discord server is running, please send me an invite :D

**Comment by jcklpe** [comment] 2019-11-29 19:03
This project looks cool. Anyone who has the most recently maintained fork, please let us know. 

It's kind of crazy how bad pretty much all other SQL clients are, UX/UI wise.

**Comment by maniadevice** [comment] 2019-12-22 18:18
Hope this project gets revived. But in the meantime, for those looking for a linux alternative - Tableplus just released an alpha version.
https://tableplus.com/linux

**Comment by dsofeir** [comment] 2019-12-22 20:22
@maniadevice I believe advertising a product which is NOT open-source in this context is inappropriate and you should remove or clarify your comment.

**Comment by maniadevice** [comment] 2019-12-22 20:48
Sure, I can clarify. 
I am not advertising this product. I am not associated with them in any way, nor am I getting any benefit out of it.
Yes, it's not an open source product. I am a Linux user and a lot of people here have mentioned how helpful sqlectron was to them. I have only tried to help them by suggesting a (currently) free product, that they could use - maybe until sqlectron is back to being actively maintained.

I'll be glad to remove the comment if one of the members are also offended it. No problem at all.

**Comment by dsofeir** [comment] 2019-12-22 22:12
Thank you @maniadevice for the clarification. I only objected because your initial comment had the appearance of an advertisement for a commercial product.

**Comment by albertotorresfoltyn** [comment] 2020-05-05 01:50
I can be a part time mantainer

**Comment by rathboma** [comment] 2020-05-07 02:22
Hey everyone.

I wanted to write you all with an apology and a reason for why I haven't contributed much to this GUI.

Back in 2019 when I tried to get involved in Sqlectron I totally underestimated the learning curve of Electron, Electron Builder, and React. Honestly I was totally unable to solve even simple problems.

I started playing with the SQLectron core libraries in a new Vue electron project to sort of figure out how everything should fit together.

In the end, the out of date dependencies and React-based UI was too much for me. So in collaboration with a friend I decided to build a fresh UI on top of the Sqlectron core libraries. I released the app a couple of weeks ago - beekeeperstudio.io.

If you look at the Github the commit history the code is a fork of sqlectron-core. So in a very real way it is a continuation of Sqlectron.

I'm sure many of you might be disappointed by my actions. I understand that. Thanks for being a welcoming community either way. I plan on continuing maintenance of Beekeeper Studio and hope some of you might become part of the project.

Thanks again.

Matthew

**Comment by MasterOdin** [comment] 2020-05-27 23:07
I chatted with @maxcnunes and will be taking over maintence of sqlectron project. A new release should be forthcoming later on this week which will have a number of fixes and features. Will leave this open for now, in case some other people are inspired to contribute.

**Comment by tomgs** [comment] 2020-06-02 12:10
Downloading now - let's see what gives! Been looking for a SequelPro alternative ever since coming over to Ubuntu.

**Comment by austinwilcox** [comment] 2020-07-13 19:15
@MasterOdin Still looking for more contributors? I use this tool daily on my linux and mac machines and I'd love to contribute some code to the project.

**Comment by albertotorresfoltyn** [comment] 2020-07-20 23:05
> @MasterOdin Still looking for more contributors? I use this tool daily on my Linux and mac machines and I'd love to contribute some code to the project.

Would you like to start a fork and work from there? I'm in a similar situation here

**Comment by MasterOdin** [comment] 2020-07-21 07:55
More the merrier, feel free on making PRs and such. I'm looking to release 1.31.0 in a day or so as it's got a nice bit of improvements here:

<details><summary>1.31.0 changelog</summary>
<p>

* Add option to list connections instead of rendering cards (#425) - by @barneydmedia  
* Allow custom UI fonts (#330) - by @barneydmedia  
* Single clicking table name runs a default query - by @barneydmedia  
* Fix NaN error on zoomFactor label on first startup (#457) - by @barneydmedia  
* Fix query results error if no custom font is set (#470) - by @rathboma  
* Move from Travis / appveyor to GH actions for CI (#492) - by @MasterOdin  
* Update node-sass to 4.14.0 (#486) - by @MasterOdin  
* Update axios to 0.19.2 (#489) - by @MasterOdin  
* Update electron-builder to 21.2.0 (#491) - by @MasterOdin  
* Add MariaDB to server type dropdown (functionally equivalent to selecting MySQL) - by @MasterOdin  
* Update sqlectron-core to 8.1.1 (#484) - by @MasterOdin  
  * Add cassandra authentication support  
  * Support MySQL caching_sha2_password authentication (default for MySQL 8)  
  * Add official support for MySQL 8  
  * Add official support for PostgreSQL 12  
  * Add official support for cassandra 2.x and 3.10+  
  * Add official support for MariaDB 10.1+  
  * Fix regression on querying information_schema tables on MySQL 8  
  * Fix not being able to specify socket without a port - by @rathboma  
  * Use ordinal_position to order column listing for all postgres, mysql, and sqlserver  
  * Fix truncateAllTables for sqlserver not working with foreign key constraints  
  * Fix sqlserver breaking if using CS collation  
</p>
</details>

I've started triaging issues for a 1.32.0 release, but the focus for me is principally on upgrading electron to the newest version and adding official support for CockroachDB. The following release I plan to begin work on upgrading react to a newer version.

**Comment by jamesanto** [comment] 2020-08-04 08:09
@MasterOdin Anything I could do to get 1.31.0 released?

**Comment by jamesanto** [comment] 2020-08-04 08:09
Ah, never mind, it's already released.

**Comment by MasterOdin** [comment] 2020-08-06 16:45
Yup, and progress is steadily being made to a quicker 1.32.0 follow-up. While I was somewhat planning on trying to add more official cockroach and redshift support in this version, I think I might hold off and get 1.32.0 out quicker to hopefully resolve the usage problems people were seeing with dependencies and such.

**Closed** 2021-03-04 00:14 UTC
