### ISSUE TITLE
No schema information for PostgreSQL database

### ISSUE THREAD

**Issue by iwozzy** [sqlectron/sqlectron-gui#255] opened 2016-10-12 20:09 UTC
I've connected to two different PostgreSQL databases. For both of them I couldn't see any tables. One was hosted by ElephantSQL and the other was a Redshift instance.

I've tried the above with v1.15.0 as well as v.1.7.0 and the results were the same.

![image](https://cloud.githubusercontent.com/assets/4137844/19325788/98a915ea-907c-11e6-836f-a7fcd5e6f772.png)

I've also connected to one of the databases above using pgAdmin 4 and noticed that is has two schema. The `public` scheme indeed has no tables. However the `dotnet` schema has all the tables that I'm after.

![image](https://cloud.githubusercontent.com/assets/4137844/19327458/fd5314c6-9083-11e6-833d-104fdc383f01.png)

--- 
I've also connected to a SQL Server and the tables were coming in fine.

**Comment by maxcnunes** [comment] 2016-10-12 21:07
@eMerzh has added schema support for good part of the app. But we have not released those changes yet. @eMerzh do you know if your changes solve this problem?

**Comment by eMerzh** [comment] 2016-10-13 08:53
@maxcnunes the change might help a bit but won't fix the issue...
because it's not yet included in -gui ...
we need to add a schema selection in the connection or in the browser somewhere ...
didn't had too much time these days but i'll try to add it at the connection level since in the browser there is a lot more to change ....


Btw i'll close this as it's a duplicate of  #153

**Closed by eMerzh** 2016-10-13 08:53 UTC
