### ISSUE TITLE
Error: Cannot find module 'lodash.clonedeep'

### ISSUE THREAD

**Issue by Klaboe** [sqlectron/sqlectron-gui#680] opened 2021-08-16 14:33 UTC
Just installed 1.37 and i get this error on startup:

![Screenshot 2021-08-16 163236](https://user-images.githubusercontent.com/126390/129580635-a6f2e8fe-4f83-4726-9e4b-21955766eae7.png)

**Comment by MasterOdin** [comment] 2021-08-16 16:50
Duplicate of #678. I've made release [v1.37.1](https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.37.1) with the fix.

**Closed by MasterOdin** 2021-08-16 16:50 UTC
