### ISSUE TITLE
Cannot connect to mysql db in localhost

### ISSUE THREAD

**Issue by superPershing** [sqlectron/sqlectron-gui#442] opened 2018-06-14 03:45 UTC
Sqlectron always return 
```
Connection Error
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
![sqlectron_mysql](https://user-images.githubusercontent.com/15770165/41390483-6daea724-6fc8-11e8-8374-e232c56d82ca.png)

I use mysql:
```
mysql  Ver 8.0.11 for Linux on x86_64 (MySQL Community Server - GPL)
```
My linux version info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
And Sqlectron work well in my another computer, which is `ubuntu 16.04 LTS, mysql 8.0`.

**Comment by barneydmedia** [comment] 2018-09-07 19:21
I'm not able to reproduce this on the latest docker mysql image, but I've seen this issue before. 

The more recent versions of MySQL use different auth plugins by default, and unfortunately it looks like the mysqljs and mysql2 don't support it yet. This isn't something this project can address directly, so we have to wait for fixes to one of those packages.

The good news that I can give is that [there are workarounds](https://github.com/mysqljs/mysql/issues/1507), mostly configuring MySQL to use the older auth systems by default. I'll leave this issue open until we can bring in a fix but I'll close duplicates.

**Comment by barneydmedia** [comment] 2018-10-04 23:46
Minor update on this, there is a PR for the mysql adapter that fixes this problem by adding in new auth compatibility. Once it's completed and merged in we can we can update the package dependency here and release a new build.

https://github.com/mysqljs/mysql/pull/1962

**Closed** 2020-05-25 22:07 UTC
Labels: bug
