### ISSUE TITLE
Query Tabs Vertically Stacking - v1.31.0

### ISSUE THREAD

**Issue by imeidopf** [sqlectron/sqlectron-gui#521] opened 2020-09-02 03:02 UTC
![Capture](https://user-images.githubusercontent.com/10743319/91927291-1852e200-eca7-11ea-95bf-c12f8266c48d.PNG)

Tabs not working as in v1.30.0. Endless stacking on new tab creation.

**Comment by arturock** [comment] 2020-09-02 22:09
Duplicate of #509

**Comment by MasterOdin** [comment] 2020-09-04 02:22
Yup, duplicate, will be fixed in 1.32.0 (already fixed in master).

**Closed by MasterOdin** 2020-09-04 02:22 UTC
