### ISSUE TITLE
Windows Went Blank?

### ISSUE THREAD

**Issue by kayzweller** [sqlectron/sqlectron-gui#601] opened 2021-03-16 00:25 UTC
after executing USE <some_db_name>;
windows went blank, the only way to solve? open new windows.
Is this just a common problem, thanks.

**Comment by MasterOdin** [comment] 2021-03-16 00:56
It's because the `use` query is causing an error within react that's causing sqlectron to soft crash.

Duplicate of #573

**Closed** 2021-03-18 21:01 UTC
